kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes: 
- role: control-plane
  extraMounts:
  - hostPath: /usr/bin
    containerPath: /bin
  - hostPath: /usr/sbin
    containerPath: /sbin
- role: worker
  extraMounts:
  - hostPath: /usr/bin
    containerPath: /bin
  - hostPath: /usr/sbin
    containerPath: /sbin
